defmodule BernardCore.Schema do
  @moduledoc """
  Base for all Ecto schemas in our App. Currently used to enact autogenerated UUIDs

    * https://hexdocs.pm/ecto/Ecto.Schema.html
    * https://blog.fourk.io/uuids-as-primary-keys-in-phoenix-with-ecto-and-elixir-1dd79e1ecc2e
  """

  defmacro __using__(_) do
    quote do
      use Ecto.Schema

      @primary_key {:id, :binary_id, autogenerate: true}
      @foreign_key_type :binary_id
    end
  end
end
